language: java
install: true
os: linux
dist: trusty
jdk:
  - oraclejdk8

jobs:
  include:
    - stage: consumer-create-contracts
      script: ./gradlew :account-service:test
    - stage: provider-contract-verification
      script: ./gradlew :user-service:test
